name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

  pod-lib-lint:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Bundler
      run: bundle update --bundler
    - name: Install Ruby gems with Bundler
      run: bundle install
    - name: Lint podspec using local source
      run: pod lib lint --verbose --allow-warnings

  spm-build-test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build unit test target
      run: swift build
    - name: Run unit test target
      run: swift test
